#! /bin/bash

DIR=`cat version.txt | tr " " "_"`

##
DOC=$DIR/doc
GDOC=$DOC/german
TGZ=$DIR.tgz

mkdir -p $DIR
mkdir -p $DOC
mkdir -p $GDOC


cp *.py version.txt $DIR

mkdir -p $DIR/Extensions
cp Extensions/*.py $DIR/Extensions

mkdir -p $DIR/help
cp help/*.html $DIR/help

mkdir -p $DIR/tests
cp tests/*.py $DIR/tests

mkdir -p $DIR/www
cp www/*.zpt www/*.png www/*.gif $DIR/www

cp doc/CHANGES.txt $DOC
cp doc/INSTALL.txt $DOC
cp doc/LICENSE.txt $DOC
cp doc/update.txt $DOC
cp doc/README.txt $DIR
cp doc/USAGE.txt $DIR


cp doc/analyse.txt $GDOC
cp doc/design.txt $GDOC
cp doc/inputKonverter.txt $GDOC


tar -czf $TGZ $DIR
rm -rf $DIR

scp $TGZ download.gocept.com:/srv/www/download.gocept.com/htdocs/packages

rm $TGZ
